<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBIeOWrt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBIeOWrt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBIeOWrt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBIeOWrt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBIeOWrt\App_KernelDevDebugContainer([
    'container.build_hash' => 'BIeOWrt',
    'container.build_id' => '7a64c757',
    'container.build_time' => 1619102235,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBIeOWrt');
